/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_COMMA = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_SEMI = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_quoted_string_token1 = 9,
  anon_sym_SQUOTE = 10,
  aux_sym_single_quoted_string_token1 = 11,
  sym_unquoted_string = 12,
  sym_number = 13,
  sym_escape_sequence = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  sym_byte = 17,
  sym_line_comment = 18,
  sym_block_comment = 19,
  sym_source_file = 20,
  sym__value = 21,
  sym_array = 22,
  sym_dictionary = 23,
  sym_dictionary_entry = 24,
  sym_string = 25,
  sym_quoted_string = 26,
  sym_single_quoted_string = 27,
  sym_data = 28,
  sym_comment = 29,
  aux_sym_array_repeat1 = 30,
  aux_sym_dictionary_repeat1 = 31,
  aux_sym_quoted_string_repeat1 = 32,
  aux_sym_single_quoted_string_repeat1 = 33,
  aux_sym_data_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_quoted_string_token1] = "single_quoted_string_token1",
  [sym_unquoted_string] = "unquoted_string",
  [sym_number] = "number",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_byte] = "byte",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__value] = "_value",
  [sym_array] = "array",
  [sym_dictionary] = "dictionary",
  [sym_dictionary_entry] = "dictionary_entry",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_data] = "data",
  [sym_comment] = "comment",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_dictionary_repeat1] = "dictionary_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_single_quoted_string_repeat1] = "single_quoted_string_repeat1",
  [aux_sym_data_repeat1] = "data_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_quoted_string_token1] = aux_sym_single_quoted_string_token1,
  [sym_unquoted_string] = sym_unquoted_string,
  [sym_number] = sym_number,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_byte] = sym_byte,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__value] = sym__value,
  [sym_array] = sym_array,
  [sym_dictionary] = sym_dictionary,
  [sym_dictionary_entry] = sym_dictionary_entry,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_data] = sym_data,
  [sym_comment] = sym_comment,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_dictionary_repeat1] = aux_sym_dictionary_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_single_quoted_string_repeat1] = aux_sym_single_quoted_string_repeat1,
  [aux_sym_data_repeat1] = aux_sym_data_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_unquoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_byte] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_data_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 24,
        '\'', 26,
        '(', 17,
        ')', 19,
        ',', 18,
        '-', 8,
        '/', 3,
        ';', 23,
        '<', 39,
        '=', 22,
        '>', 40,
        '\\', 7,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(25);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(27);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '>') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == 'U') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(37);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 24,
        '\'', 26,
        '(', 17,
        ')', 19,
        ',', 18,
        '-', 8,
        '/', 3,
        ';', 23,
        '<', 39,
        '=', 22,
        '>', 40,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 24,
        '\'', 26,
        '(', 17,
        ')', 19,
        '-', 8,
        '/', 28,
        '<', 39,
        '{', 20,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('.' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_single_quoted_string_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_unquoted_string);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead == '$' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_byte);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_byte] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__value] = STATE(42),
    [sym_array] = STATE(27),
    [sym_dictionary] = STATE(27),
    [sym_string] = STATE(27),
    [sym_quoted_string] = STATE(14),
    [sym_single_quoted_string] = STATE(14),
    [sym_data] = STATE(27),
    [sym_comment] = STATE(1),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_unquoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(21),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__value] = STATE(41),
    [sym_array] = STATE(27),
    [sym_dictionary] = STATE(27),
    [sym_string] = STATE(27),
    [sym_quoted_string] = STATE(14),
    [sym_single_quoted_string] = STATE(14),
    [sym_data] = STATE(27),
    [sym_comment] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_unquoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(21),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__value] = STATE(41),
    [sym_array] = STATE(27),
    [sym_dictionary] = STATE(27),
    [sym_string] = STATE(27),
    [sym_quoted_string] = STATE(14),
    [sym_single_quoted_string] = STATE(14),
    [sym_data] = STATE(27),
    [sym_comment] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_unquoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(21),
    [sym_block_comment] = ACTIONS(5),
  },
  [STATE(4)] = {
    [sym__value] = STATE(34),
    [sym_array] = STATE(27),
    [sym_dictionary] = STATE(27),
    [sym_string] = STATE(27),
    [sym_quoted_string] = STATE(14),
    [sym_single_quoted_string] = STATE(14),
    [sym_data] = STATE(27),
    [sym_comment] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_unquoted_string] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(21),
    [sym_block_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      sym_unquoted_string,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_line_comment,
    STATE(5), 1,
      sym_comment,
    STATE(44), 1,
      sym__value,
    ACTIONS(5), 2,
      anon_sym_LPAREN,
      sym_block_comment,
    STATE(14), 2,
      sym_quoted_string,
      sym_single_quoted_string,
    STATE(27), 4,
      sym_array,
      sym_dictionary,
      sym_string,
      sym_data,
  [42] = 12,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      sym_unquoted_string,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_line_comment,
    STATE(6), 1,
      sym_comment,
    STATE(41), 1,
      sym__value,
    ACTIONS(5), 2,
      anon_sym_LPAREN,
      sym_block_comment,
    STATE(14), 2,
      sym_quoted_string,
      sym_single_quoted_string,
    STATE(27), 4,
      sym_array,
      sym_dictionary,
      sym_string,
      sym_data,
  [84] = 10,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(34), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      sym_unquoted_string,
    STATE(24), 1,
      sym_dictionary_entry,
    STATE(43), 1,
      sym_string,
    STATE(7), 2,
      sym_comment,
      aux_sym_dictionary_repeat1,
    STATE(14), 2,
      sym_quoted_string,
      sym_single_quoted_string,
  [117] = 11,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      sym_unquoted_string,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_dictionary_repeat1,
    STATE(24), 1,
      sym_dictionary_entry,
    STATE(43), 1,
      sym_string,
    STATE(14), 2,
      sym_quoted_string,
      sym_single_quoted_string,
  [152] = 11,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      sym_unquoted_string,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_dictionary_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(24), 1,
      sym_dictionary_entry,
    STATE(43), 1,
      sym_string,
    STATE(14), 2,
      sym_quoted_string,
      sym_single_quoted_string,
  [187] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(10), 1,
      sym_comment,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SEMI,
  [204] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(11), 1,
      sym_comment,
    ACTIONS(46), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SEMI,
  [221] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(12), 1,
      sym_comment,
    ACTIONS(48), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SEMI,
  [238] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(13), 1,
      sym_comment,
    ACTIONS(50), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SEMI,
  [255] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(14), 1,
      sym_comment,
    ACTIONS(52), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_SEMI,
  [272] = 6,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      sym_block_comment,
    STATE(15), 1,
      sym_comment,
    STATE(20), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(56), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [292] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(16), 1,
      sym_comment,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [308] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(17), 1,
      sym_comment,
    ACTIONS(62), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [324] = 6,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(64), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_single_quoted_string_repeat1,
    ACTIONS(66), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
  [344] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(19), 1,
      sym_comment,
    ACTIONS(68), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [360] = 6,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(70), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_quoted_string_repeat1,
    ACTIONS(56), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [380] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(21), 1,
      sym_comment,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [396] = 6,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(74), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      aux_sym_single_quoted_string_repeat1,
    STATE(22), 1,
      sym_comment,
    ACTIONS(66), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
  [416] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(23), 1,
      sym_comment,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [432] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(80), 1,
      sym_unquoted_string,
    STATE(24), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [450] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
    STATE(25), 2,
      sym_comment,
      aux_sym_quoted_string_repeat1,
  [468] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(26), 1,
      sym_comment,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [484] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(27), 1,
      sym_comment,
    ACTIONS(89), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [500] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(91), 1,
      anon_sym_SQUOTE,
    ACTIONS(93), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
    STATE(28), 2,
      sym_comment,
      aux_sym_single_quoted_string_repeat1,
  [518] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(29), 1,
      sym_comment,
    ACTIONS(96), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [534] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(30), 1,
      sym_comment,
    ACTIONS(98), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [550] = 5,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(102), 1,
      sym_unquoted_string,
    STATE(31), 1,
      sym_comment,
    ACTIONS(100), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [568] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(104), 1,
      anon_sym_GT,
    ACTIONS(106), 1,
      sym_byte,
    STATE(32), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_data_repeat1,
  [587] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(108), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_comment,
    ACTIONS(110), 2,
      aux_sym_quoted_string_token1,
      sym_escape_sequence,
  [604] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(112), 1,
      anon_sym_COMMA,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_comment,
    STATE(36), 1,
      aux_sym_array_repeat1,
  [623] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(58), 1,
      sym_block_comment,
    ACTIONS(116), 1,
      anon_sym_SQUOTE,
    STATE(35), 1,
      sym_comment,
    ACTIONS(118), 2,
      aux_sym_single_quoted_string_token1,
      sym_escape_sequence,
  [640] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      sym_comment,
    STATE(37), 1,
      aux_sym_array_repeat1,
  [659] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    STATE(37), 2,
      sym_comment,
      aux_sym_array_repeat1,
  [676] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(127), 1,
      anon_sym_GT,
    ACTIONS(129), 1,
      sym_byte,
    STATE(38), 2,
      sym_comment,
      aux_sym_data_repeat1,
  [693] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(106), 1,
      sym_byte,
    ACTIONS(132), 1,
      anon_sym_GT,
    STATE(32), 1,
      aux_sym_data_repeat1,
    STATE(39), 1,
      sym_comment,
  [712] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(40), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_GT,
      sym_byte,
  [726] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(41), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [740] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      sym_comment,
  [753] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(138), 1,
      anon_sym_EQ,
    STATE(43), 1,
      sym_comment,
  [766] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_comment,
  [779] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(45), 1,
      sym_comment,
  [792] = 1,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 84,
  [SMALL_STATE(8)] = 117,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 187,
  [SMALL_STATE(11)] = 204,
  [SMALL_STATE(12)] = 221,
  [SMALL_STATE(13)] = 238,
  [SMALL_STATE(14)] = 255,
  [SMALL_STATE(15)] = 272,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 308,
  [SMALL_STATE(18)] = 324,
  [SMALL_STATE(19)] = 344,
  [SMALL_STATE(20)] = 360,
  [SMALL_STATE(21)] = 380,
  [SMALL_STATE(22)] = 396,
  [SMALL_STATE(23)] = 416,
  [SMALL_STATE(24)] = 432,
  [SMALL_STATE(25)] = 450,
  [SMALL_STATE(26)] = 468,
  [SMALL_STATE(27)] = 484,
  [SMALL_STATE(28)] = 500,
  [SMALL_STATE(29)] = 518,
  [SMALL_STATE(30)] = 534,
  [SMALL_STATE(31)] = 550,
  [SMALL_STATE(32)] = 568,
  [SMALL_STATE(33)] = 587,
  [SMALL_STATE(34)] = 604,
  [SMALL_STATE(35)] = 623,
  [SMALL_STATE(36)] = 640,
  [SMALL_STATE(37)] = 659,
  [SMALL_STATE(38)] = 676,
  [SMALL_STATE(39)] = 693,
  [SMALL_STATE(40)] = 712,
  [SMALL_STATE(41)] = 726,
  [SMALL_STATE(42)] = 740,
  [SMALL_STATE(43)] = 753,
  [SMALL_STATE(44)] = 766,
  [SMALL_STATE(45)] = 779,
  [SMALL_STATE(46)] = 792,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_string, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_string, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_repeat1, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_quoted_string_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_single_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_entry, 4, 0, 1),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_entry, 4, 0, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_quoted_string_repeat1, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_single_quoted_string_repeat1, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_data_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_data_repeat1, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [142] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_property_list(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "property_list",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
